apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: airflow-helm-repo1
  namespace: ns-cs9-test
spec:
  interval: 1m
  url: https://airflow.apache.org
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: ns-cs9-test
spec:
  releaseName: airflow
  interval: 5m
  timeout: 11m  
  chart:
    spec:
      chart: airflow
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: airflow-helm-repo1
        namespace: ns-cs9-test
  values:
    airflow:
    users:
      - username: admin2
        password: admin2
        role: Admin
        email: admin@example2.com
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false
    startupProbe:
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      timeoutSeconds: 60
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 20
