apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: airflow-helm-repo
  namespace: ns-cs9-test
spec:
  interval: 1m
  url: https://airflow.apache.org
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: ns-cs9-test
spec:
  releaseName: airflow
  interval: 5m
  timeout: 11m  
  chart:
    spec:
      chart: airflow
      version: 8.5.3
      sourceRef:
        kind: HelmRepository
        name: airflow-helm-repo
        namespace: ns-cs9-test
  values:
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false
    service:
      type: ClusterIP
    dags:
      persistence:
        enabled: true
        size: 1Gi
    workers:
      replicas: 1
    executor: "KubernetesExecutor"
    redis:
      enabled: true
    postgresql:
      enabled: true
