apiVersion: source.toolkit.fluxcd.io/v1
# view config doc here: https://github.com/apache/airflow/blob/main/chart/values.yaml
kind: HelmRepository
metadata:
  name: airflow-helm-repo2
  namespace: ns-cs9-test
spec:
  interval: 1m
  url: https://airflow.apache.org
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: ns-cs9-test
spec:
  releaseName: airflow
  interval: 5m
  timeout: 5m  
  chart:
    spec:
      chart: airflow
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: airflow-helm-repo2
        namespace: ns-cs9-test
  values:
    dags:
      persistence:
        enabled: false  # Disable DAG volume mount that would override gitSync
      gitSync:
        enabled: true
        repo: https://github.com/FHIDev/FHI.Fida.cs.git
        branch: skybert-airflow-dags
        subPath: ""  # if your DAG files are inside a 'dags/' folder in the repo root
        depth: 1

    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false
    postgresql:
      enabled: false
    redis:
      enabled: true
    webserver:
      extraVolumes:
        - name: webserver-config
          configMap:
            name: airflow-webserver-config
      extraVolumeMounts:
        - name: webserver-config
          mountPath: /opt/airflow/webserver_config.py
          subPath: webserver_config.py
          readOnly: true
      env:
        - name: AZURE_AD_TENANT_ID
          value: "54475f80-1baa-4ea9-9185-c0de5cc603fe"
        - name: AZURE_AD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: airflow-azure-secrets
              key: client-id
        - name: AZURE_AD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: airflow-azure-secrets
              key: client-secret

    data:
      metadataConnection:
         user: altformyerettigheter
         pass: portalazurecomcreateMicrosoftPostgreSQLServer
         protocol: postgresql
         host: airflow-cs9-test.postgres.database.azure.com
         port: 5432
         db: postgres
         sslmode: prefer
