apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-cs9an-test
#    fluentbit.fluent.io/enabled: "true"
  name: deployment-cs9an-test
  namespace: ns-cs9-test
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: app-cs9an-test
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-cs9an-test
#        fluentbit.fluent.io/enabled: "true"
    spec:
      containers:
      - image: apache/airflow:2.10.5
        imagePullPolicy: Always
        name: ct-cs9an-webserver
        command: ["webserver"]
        ports:
        - containerPort: 8080
          name: cs9an-port
        env:
          - name: AIRFLOW__CORE__EXECUTOR
            value: "CeleryExecutor"
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
          - name: AIRFLOW__CELERY__RESULT_BACKEND
            value: "db+postgresql://airflow:airflow@postgres/airflow"
          - name: AIRFLOW__CELERY__BROKER_URL
            value: "redis://:@redis:6379/0"
          - name: AIRFLOW__CORE__FERNET_KEY
            value: ""
          - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
            value: "true"
          - name: AIRFLOW__CORE__LOAD_EXAMPLES
            value: "true"
          - name: AIRFLOW__API__AUTH_BACKENDS
            value: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
          - name: AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK
            value: "true"
          - name: _PIP_ADDITIONAL_REQUIREMENTS
            value: "${_PIP_ADDITIONAL_REQUIREMENTS:-}"
        resources:
#          limits:
#            cpu: 4000m
#            memory: 8192Mi
          requests:
            cpu: 2000m
            memory: 4096Mi
        volumeMounts:
        - mountPath: /secrets/
          name: volume-akv-secret-1
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          nodePublishSecretRef:
            name: secret-akv-sp           # Service principal secret
          readOnly: true
          volumeAttributes:
            secretProviderClass: akv-cs9-test
        name: volume-akv-secret-1
