apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secretproviderclass.yaml
  - rolebinding.yaml
  - wn-deployment.yaml
  - wn-service.yaml
  - wn-ingress.yaml
  - airflow1.yaml
  - an-ingress.yaml
# nameSuffix: test
namespace: ns-cs9-test
#commonLabels:
#  app: app-cs9-test
