apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secretproviderclass.yaml
  - rolebinding.yaml
  - wn-deployment.yaml
  - wn-service.yaml
  - wn-ingress.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-init-configmap.yaml
  - airflow1.yaml
  - airflow1-with-oauth.yaml
  - airflow-pod-template-configmap.yaml
  - an-ingress.yaml
namespace: ns-cs9-test
#commonLabels:
#  app: app-cs9-test
