apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: ns-cs9-test
data:
  init.sql: |
    -- Grant permissions to the user on default postgres database
    GRANT ALL PRIVILEGES ON DATABASE postgres TO yourusername;
