apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-cs9-test
  namespace: ns-cs9-test
spec:
  provider: azure
  secretObjects:
  - secretName: sync-example
    data:
    - key: value
      objectName: posit-license
    type: Opaque
  - secretName: airflow-azure-secrets
    data:
    - key: client-id
      objectName: openid-client-id
    - key: client-secret
      objectName: openid-client-secret
    type: Opaque
  parameters:
    usePodIdentity: "false"               # [OPTIONAL] if not provided, will default to "false"
#    useVMManagedIdentity: "true"         # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
#    userAssignedIdentityID: "392c9c59-e579-4dd1-bc9f-e0b7c1d29f60"   # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
#    userAssignedIdentityID: "502bfbe1-c14e-4fc6-9319-53d34cfe295a"   # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
#    clientID: "502bfbe1-c14e-4fc6-9319-53d34cfe295a"                 # [OPTIONAL available for version > 1.1.0] client id of the Azure AD Application or managed identity to use for workload identity
    keyvaultName: "akv-cs9-test"           # the name of the KeyVault
#    cloudName: ""                         # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
#    cloudEnvFileName: ""                  # [OPTIONAL available for version > 0.0.7] use to define path to file for populating azure environment
    objects:  |
      array:
        - |
          objectName: posit-license
          objectType: secret              # object types: secret, key or cert. For Key Vault certificates, refer to https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/getting-certs-and-keys/ for the object type to use
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: openid-client-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: openid-client-id
          objectType: secret
          objectVersion: ""
#          objectAlias: "alias-name"      # Replaces objectname
#        - |
#          objectName: key1
#          objectAlias: ""                 # If provided then it has to be referenced in [secretObjects].[objectName] to sync with Kubernetes secrets 
#          objectType: key
#          objectVersion: ""
    
#    resourceGroup: "rg-fhi-fts-arc-vmware-poc"
#    subscriptionId: "19b353ae-492d-43cb-bcf0-3ecc642c55da"
    tenantID: "54475f80-1baa-4ea9-9185-c0de5cc603fe"                       # the tenant ID of the KeyVault
