{{/*
Generate ServiceAccount resources for each team
*/}}
{{- range .Values.teams }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.serviceAccount.namePrefix }}{{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    azure.workload.identity/client-id: "{{ .clientId }}"
    {{- with $.Values.serviceAccount.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- with $.Values.serviceAccount.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    team: "{{ .name }}"
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: service-account
{{- end }}