name: Build csbase

env:
  VERSION: 4.4.1

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"  # Runs every day at 18:00 UTC (6:00 PM UTC)

concurrency:
  group: cs9base

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    
    - name: Switch to cs9base-${{ env.VERSION }} branch
      run: git fetch && git checkout cs9base-${{ env.VERSION }}

    - name: Set lowercase repository name as environment variable
      run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the image
      run: cd image && docker build . --tag cs9base:${{ env.VERSION }}

    - name: Build the image
      run: cd image && docker build . --tag ghcr.io/${{ env.REPO_NAME }}/cs9base:${{ env.VERSION }}
        
    - name: Push the image to GHCR (versioned)
      run: docker push ghcr.io/${{ env.REPO_NAME }}/cs9base:${{ env.VERSION }}    
      
    - name: Retag and push image (latest)
      run: |
        docker tag ghcr.io/${{ env.REPO_NAME }}/cs9base:${{ env.VERSION }} ghcr.io/${{ env.REPO_NAME }}/cs9base:latest
        docker push ghcr.io/${{ env.REPO_NAME }}/cs9base:latest
      
    - name: Clean up untagged images
      uses: actions/delete-package-versions@v5
      with: 
        package-name: 'fhi.fida.cs/cs9base'
        package-type: 'container'
        min-versions-to-keep: 0
        delete-only-untagged-versions: 'true'
