name: Build csbase

on:
  push:
    branches: [ "cs9base-*" ]
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"  # Runs every day at 18:00 UTC (6:00 PM UTC)
    
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Extract version from branch name
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/heads/cs9base-}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: cd image && docker build . --tag cs9base:${{ env.VERSION }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        repo_lower=$(echo "${GITHUB_REPOSITORY,,}")
        cd image
        docker build . --tag ghcr.io/${repo_lower}/cs9base:${{ env.VERSION }}
        
    - name: Push the Docker image to GHCR
      run: |
        repo_lower=$(echo "${GITHUB_REPOSITORY,,}")
        docker push ghcr.io/${repo_lower}/cs9base:${{ env.VERSION }}      
        
