name: Build csbase

on:
  push:
    branches: [ "cs9base-*" ]
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"  # Runs every day at 18:00 UTC (6:00 PM UTC)

concurrency:
  group: cs9base-${{ github.ref }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Extract version from branch name
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/heads/cs9base-}" >> $GITHUB_ENV

    - name: Set lowercase repository name as environment variable
      run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: cd image && docker build . --tag cs9base:${{ env.VERSION }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: cd image && docker build . --tag ghcr.io/${{ env.REPO_NAME }}/cs9base:${{ env.VERSION }}
        
    - name: Push the Docker image to GHCR
      run: docker push ghcr.io/${{ env.REPO_NAME }}/cs9base:${{ env.VERSION }}        
      
    - name: Clean up untagged Docker images
      run: |
        # Fetch all images and filter out the ones with no tags
        images=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/orgs/FHIDev/packages/container/fhi.fida.cs/versions" \
          | jq -r '.[] | select(.metadata.container.tags == null) | .id')
    
        # Loop through the untagged images and delete them
        for image_id in $images; do
          curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/orgs/FHIDev/packages/container/fhi.fida.cs/versions/$image_id"
        done
