name: Build csbase

on:
  push:
    branches: [ "csworkbench" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: cd image & docker build --tag csworkbench:latest
