name: Build csworkbench

on:
  push:
    branches: [ "csworkbench" ]
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"  # Runs every day at 19:00 UTC (7:00 PM UTC)

concurrency:
  group: csworkbench-${{ github.ref }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set lowercase repository name as environment variable
      run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: cd image && docker build . --tag csworkbench:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: cd image && docker build . --tag ghcr.io/${{ env.REPO_NAME }}/csworkbench:latest
        
    - name: Push the Docker image to GHCR
      run: docker push ghcr.io/${{ env.REPO_NAME }}/csworkbench:latest     
      
    - name: Clean up untagged Docker images
      uses: actions/delete-package-versions@v5
      with: 
        package-name: 'fhi.fida.cs/csworkbench'
        package-type: 'container'
        min-versions-to-keep: 0
        delete-only-untagged-versions: 'true'

