name: Docker Image CI

on:
  push:
    branches: [ "cs9base-4.4.1" ]
  pull_request:
    branches: [ "cs9base-4.4.1" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file image/Dockerfile --tag cs9base:4.4.1
