name: Docker Image CI

on:
  push:
    branches: [ "cs9base-*" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract version from branch name
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/heads/cs9base-}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file image/Dockerfile --tag cs9base:${{ env.VERSION }}
